### ISSUE TITLE
Modify the tests pom.xml to setup JUnit

### ISSUE THREAD

**Issue by Isigiel** [oberrich/artemis_cli#17]
I'll outline how to modify the `pom.xml` contained in the `tests` repository to work in the root of a student repo and allow the running of `tutortests` without any more specific setup.
This installs all the maven deps the tests need when the project is opened.

**In the `<build>` section:**
Remove the `<testSourceDirectory>` and `<testResources>` tags
Adjust the path in `<sourceDirectory>`

**In the `<dependencies>` section:**
Remove any `<scope>` tags

After applying these changes the IDE should be able to correctly open the project, it would be great if the CLI could make these when setting up the tests

**Comment by oberrich** [comment]
Resolved with 335d5c85b5b3000435b2e95b825f359d56d7817d

**Comment by oberrich** [comment]
Possible enhancement: Add the tutortest folder as a test folder in maven project for better IDE support

**Comment by lgerhardt45** [comment]
Using `./artemis_cli repos -a ... -s ...` now downloads the repos and adds the testing folders to the student-assignment repo, do I understand that right? Importing the repos to Eclipse (which is the necessary workflow for grading) now yields this: 
![image](https://user-images.githubusercontent.com/40395744/69015027-512bff80-0990-11ea-9ba2-690e254d7a82.png)

The enhancement that was implemented (adding the test folders) needs to be documented in both the README and the cli-tool help sections, also explaining how to silence the warnings. A simple #**wontfix** is not an option IMO @oberrich

**Comment by oberrich** [comment]
The `link_tests` switch is automatically creating maven projects that include the required packages for testing (JUnit 4 + 5 mostly).
In order to import projects use "File -> Import -> Maven -> Existing Maven Projects -> Root Directory: /path/to/course/assignment".
The lack of documentation is already on the TODO list with issue #18
