### ISSUE TITLE
Add student id/ name to repository to allow batch import into Eclipse

### ISSUE THREAD

**Issue by lgerhardt45** [oberrich/artemis_cli#5]
# Problem: 
Batch import of student assignment repositories into Eclipse doesn't work, as all repos have the same **name** and Eclipse interprets that as projects already existing in workspace. Error message see below:
![image](https://user-images.githubusercontent.com/40395744/68536513-7eefc380-0354-11ea-9374-92a8bee59701.png)

The manual repository download from [ArTEMiS](https://artemis.ase.in.tum.de/#/course/37/exercise/743/dashboard) -> _Download repos_ has the following option (see screenshot attached)

`"Add student name to project (allows to import multiple projects into Eclipse at the same time)"`

![image](https://user-images.githubusercontent.com/40395744/68536511-77301f00-0354-11ea-958a-ebb15480a0be.png)

# Solution:
This option should be implemented in the script and set as true per default.

**Comment by oberrich** [comment]
Reference to Artemis implementation for this feature: https://github.com/ls1intum/Artemis/blob/44d869211e47d7a30dbf0ce18c60d0aa553acc2e/src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseService.java#L137

**Comment by oberrich** [comment]
Implementing this probably requires additional work. I could imagine git issues arising when changing project files locally and trying to git pull after the student has made changes on the remote.
Possible ways to overcome this:
- Check which files have been changed locally
-- if changes are limited to Eclipse fixes, undo all changes locally, then pull
-- otherwise ask the tutor if he wants to drop his local changes

**Comment by lgerhardt45** [comment]
> I could imagine git issues arising when changing project files locally and trying to git pull after the student has made changes on the remote.

I don't think this is a problem as, at the time of grading, the student isn't supposed to (and I think it was mentioned not even allowed to) push into remote after the deadline. 
If I understand the [Feature implementation in Artemis](https://github.com/ls1intum/Artemis/blob/44d869211e47d7a30dbf0ce18c60d0aa553acc2e/src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseService.java#L137) right, is that they simply search for the repo description  the XML project file and append the student id (cmp. lines 155-173). This can also be done locally, as, again, no pulling from the remote is necessary/ allowed at this point anymore.
